### ISSUE TITLE
Doesn't work on 1.20.6

### ISSUE THREAD

**Issue by ghost** [RealizedMC/Duels#119]
[07:55:46 INFO]: [Duels] Enabling Duels v3.5.3
[07:55:47 INFO]: [Duels] Successfully hooked into 'Essentials'!
[07:55:47 INFO]: [PlaceholderAPI] Successfully registered internal expansion: duels [1.0]
[07:55:47 INFO]: [Duels] Successfully hooked into 'PlaceholderAPI'!
[07:55:47 INFO]: [Duels] Successfully hooked into 'PvPManager'!
[07:55:47 INFO]: [Duels] Using Economy Provider: com.earth2me.essentials.economy.vault.VaultEconomyProvider
[07:55:47 INFO]: [Duels] Successfully hooked into 'Vault'!
[07:55:47 WARN]: [Duels] Failed to hook into WorldGuard: null
[07:55:47 ERROR]: Error occurred while enabling Duels v3.5.3 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class me.realized.duels.util.reflect.ReflectionUtil
        at Duels-3.5.3.jar/me.realized.duels.util.StringUtil.<clinit>(StringUtil.java:31) ~[Duels-3.5.3.jar:?]
        at Duels-3.5.3.jar/me.realized.duels.config.Lang.loadValues(Lang.java:54) ~[Duels-3.5.3.jar:?]
        at Duels-3.5.3.jar/me.realized.duels.util.config.AbstractConfiguration.handleLoad(AbstractConfiguration.java:65) ~[Duels-3.5.3.jar:?]
        at Duels-3.5.3.jar/me.realized.duels.DuelsPlugin.load(DuelsPlugin.java:242) ~[Duels-3.5.3.jar:?]
        at Duels-3.5.3.jar/me.realized.duels.DuelsPlugin.onEnable(DuelsPlugin.java:175) ~[Duels-3.5.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:626) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:575) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1 [in thread "Server thread"]
        at Duels-3.5.3.jar/me.realized.duels.util.reflect.ReflectionUtil.<clinit>(ReflectionUtil.java:18) ~[Duels-3.5.3.jar:?]
        at Duels-3.5.3.jar/me.realized.duels.hook.hooks.worldguard.WorldGuardHook.<init>(WorldGuardHook.java:20) ~[Duels-3.5.3.jar:?]
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at Duels-3.5.3.jar/me.realized.duels.util.hook.AbstractHookManager.register(AbstractHookManager.java:26) ~[Duels-3.5.3.jar:?]
        at Duels-3.5.3.jar/me.realized.duels.hook.HookManager.<init>(HookManager.java:37) ~[Duels-3.5.3.jar:?]
        at Duels-3.5.3.jar/me.realized.duels.DuelsPlugin.onEnable(DuelsPlugin.java:171) ~[Duels-3.5.3.jar:?]
        ... 12 more
[07:55:47 INFO]: [Duels] Disabling Duels v3.5.3
[07:55:47 INFO]: [Duels] Disable process took 4ms.

**Comment by smscentras** [comment]
Plugin dead

**Comment by dumbo-the-developer** [comment]
Use my fork: https://modrinth.com/plugin/duels-optimised

**Comment by sprytex** [comment]
Fixed here: https://modrinth.com/plugin/duelsoptimized/version/3.5.4
